version: '3.8'

services:
    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        container_name: backend-php
        ports:
            - 5174:5173 
        volumes:
            - ./src:/var/www:cached
        networks:
            - backend-network

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx:alpine
        container_name: backend-nginx
        ports:
            - 8000:80
        volumes:
            - ./src:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        networks:
            - backend-network
        restart: unless-stopped

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        image: mysql:8.0
        container_name: backend-mysql
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_rbac
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        networks:
            - backend-network
        restart: unless-stopped

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: backend-phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            PMA_USER: laravel_user
            PMA_PASSWORD: laravel_pass
        volumes:
            - .docker/phpmyadmin/sessions:/sessions
        depends_on:
            - db
        networks:
            - backend-network
        restart: unless-stopped

    ####################################################################################################
    # Redis
    ####################################################################################################
    redis:
        image: redis:alpine
        container_name: backend-redis
        command: redis-server --appendonly yes --requirepass redispass
        volumes:
            - redis_data:/data
        ports:
            - 6379:6379
        networks:
            - backend-network
        restart: unless-stopped

    ####################################################################################################
    # Frontend App (React/Vite)
    ####################################################################################################
    frontend:
        build: ./frontend-app
        container_name: frontend-app
        ports:
            - 3000:5173
        volumes:
            - ./frontend-app:/app:cached
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
            - VITE_API_URL=http://localhost:8000/api
        networks:
            - backend-network
        restart: unless-stopped
        depends_on:
            - nginx

    ####################################################################################################
    # Adminer
    ####################################################################################################
    # adminer:
    #     image: adminer
    #     ports:
    #         - 9090:8080
    #     depends_on:
    #     - db

    ####################################################################################################
    # Mailpit
    ####################################################################################################
    # mail:
    #     image: axllent/mailpit:latest
    #     ports:
    #     - 8025:8025
    #     - 1025:1025



    # ####################################################################################################
    # # DATABASE (MariaDB)
    # ####################################################################################################
    # db:
    #     image: mariadb:10.11
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - .docker/db/data:/var/lib/mysql
    #         - .docker/logs:/var/log/mysql
    #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #         - .docker/db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_DATABASE: laravel_db_name
    #         MYSQL_USER: laravel_db_user
    #         MYSQL_PASSWORD: laravel_db_pass

    ####################################################################################################
    # PostgreSQL
    ####################################################################################################
    # db:
    #     image: postgres:16
    #     ports:
    #         - 5432:5432
    #     volumes:
    #         - .docker/db/data:/var/lib/postgresql/data
    #         - .docker/db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         - POSTGRES_USER=refactorian
    #         - POSTGRES_PASSWORD=refactorian
    #         - POSTGRES_DB=refactorian

    ####################################################################################################
    # pgAdmin
    ####################################################################################################
    # pgadmin:
    #     image: dpage/pgadmin4
    #     ports:
    #         - 5050:80
    #     environment:
    #         - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    #         - PGADMIN_DEFAULT_PASSWORD=password
    #     depends_on:
    #         - db

networks:
    backend-network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
    redis_data:
        driver: local
