name: linter

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv

      - name: Install Dependencies
        working-directory: ./src
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Run Pint
        working-directory: ./src
        run: vendor/bin/pint --test

      - name: Format Frontend
        working-directory: ./src
        run: npm run format

      - name: Lint Frontend
        working-directory: ./src
        run: npm run lint

      # Uncomment the following lines if you want auto-commit fixes
      # - name: Commit Changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: fix code style
      #     commit_options: '--no-verify'